# Generated by Django 5.0.6 on 2024-05-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_comment_comment_rating_alter_post_rating_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating_post',
            field=models.SmallIntegerField(default=0),
        ),
    ]
