# Generated by Django 5.0.6 on 2024-08-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_name_category_en_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_category',
            field=models.CharField(help_text='category name', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_category_en_us',
            field=models.CharField(help_text='category name', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_category_ru',
            field=models.CharField(help_text='category name', max_length=255, null=True, unique=True),
        ),
    ]
